<template>
  <div>
    <h1>使い方の説明</h1>
    <p>TP = タスクポイントだよ</p>
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
  </div>
</template>