<template>
  <div>
    <h1>ボスと戦う！！！</h1>
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
    <img class="mon" src="../assets/mon_178.gif">
  </div>
</template>